const products = [
    {
        title: 'Zapato1',
        img: '',
        description: 'Zapatos',
        options: [],
        genre:'',
        size:3,
        type:'clothes',
        color: 'black', 
        price: 500,
    },
    {
        title: 'Zapato2',
        img: '',
        description: 'Zapatos',
        options: [],
        genre:'',
        size:3,
        type:'clothes',
        color: 'black',
        price: 500,
    },
    {
        title: 'Zapato3',
        img: '',
        description: 'Zapatos',
        options: [],
        genre:'',
        size:3,
        type:'clothes',
        color: 'black',
        price: 500,
    },
    {
        title: 'Zapato4',
        img: '',
        description: 'Zapatos',
        options: [],
        genre:'',
        size:3,
        type:'clothes',
        color: 'black',
        price: 500,
    },
    {
        title: 'Zapato5',
        img: '',
        description: 'Zapatos',
        options: [],
        genre:'',
        size:3,
        type:'clothes',
        color: 'black',
        price: 500,
    },
    {
        title: 'Zapato6',
        img: '',
        description: 'Zapatos',
        options: [],
        genre:'',
        size:3,
        type:'clothes',
        color: 'black',
        price: 500,
    },
    {
        title: 'Zapato7',
        img: '',
        description: 'Zapatos',
        options: [],
        genre:'',
        size:3,
        type:'clothes',
        color: 'black',
        price: 500,
    },
    {
        title: 'Zapato8',
        img: '',
        description: 'Zapatos',
        options: [],
        genre:'',
        size:3,
        type:'clothes',
        color: 'black',
        price: 500,
    },
    {
        title: 'Zapato9',
        img: '',
        description: 'Zapatos',
        options: [],
        genre:'',
        size:3,
        type:'clothes',
        color: 'black',
        price: 500,
    },
    {
        title: 'Zapato10',
        img: '',
        description: 'Zapatos',
        options: [],
        genre:'',
        size:3,
        type:'clothes',
        color: 'black',
        price: 500,
    },
    {
        title: 'Zapato11',
        img: '',
        description: 'Zapatos',
        options: [],
        genre:'',
        size:3,
        type:'clothes',
        color: 'black',
        price: 500,
    },
    {
        title: 'Zapato12',
        img: '',
        description: 'Zapatos',
        options: [],
        genre:'',
        size:3,
        type:'clothes',
        color: 'black',
        price: 500,
    },
    {
        title: 'Zapato13',
        img: '',
        description: 'Zapatos',
        options: [],
        genre:'',
        size:3,
        type:'clothes',
        color: 'black',
        price: 500,
    },
    {
        title: 'Zapato14',
        img: '',
        description: 'Zapatos',
        options: [],
        genre:'',
        size:3,
        type:'clothes',
        color: 'black',
        price: 500,
    },
    {
        title: 'Zapato15',
        img: '',
        description: 'Zapatos',
        options: [],
        genre:'',
        size:3,
        type:'clothes',
        color: 'black',
        price: 500,
    },
    {
        title: 'Zapato16',
        img: '',
        description: 'Zapatos',
        options: [],
        genre:'',
        size:3,
        type:'clothes',
        color: 'black',
        price: 500,
    },
    {
        title: 'Zapato17',
        img: '',
        description: 'Zapatos',
        options: [],
        genre:'',
        size:3,
        type:'clothes',
        color: 'black',
        price: 500,
    },
    {
        title: 'Zapato18',
        img: '',
        description: 'Zapatos',
        options: [],
        genre:'',
        size:3,
        type:'clothes',
        color: 'black',
        price: 500,
    },
    {
        title: 'Zapato19',
        img: '',
        description: 'Zapatos',
        options: [],
        genre:'',
        size:3,
        type:'clothes',
        color: 'black',
        price: 500,
    },
    {
        title: 'Zapato20',
        img: '',
        description: 'Zapatos',
        options: [],
        genre:'',
        size:3,
        type:'clothes',
        color: 'black',
        price: 500,
    }
];